### ISSUE TITLE
PlayerQuitEvent Error

### ISSUE THREAD

**Issue by xDeeKay** [Scarsz/DiscordSRV#1]
Hi there, DiscordSRV throws an error when a player leaves the game. It seems to be related to ChatColor within bungee, perhaps an incorrect import?

> [01:13:29] [Server thread/INFO]: xDeeKay lost connection: Disconnected
[01:13:29] [Server thread/ERROR]: Could not pass event PlayerQuitEvent to DiscordSRV v3.0
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[craftbukkit-1.8-R0.1-SNAPSHOT.jar:git-Bukkit-994b2aa]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit-1.8-R0.1-SNAPSHOT.jar:git-Bukkit-994b2aa]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [craftbukkit-1.8-R0.1-SNAPSHOT.jar:git-Bukkit-994b2aa]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [craftbukkit-1.8-R0.1-SNAPSHOT.jar:git-Bukkit-994b2aa]
	at net.minecraft.server.v1_8_R3.PlayerList.disconnect(PlayerList.java:332) [craftbukkit-1.8-R0.1-SNAPSHOT.jar:git-Bukkit-994b2aa]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:813) [craftbukkit-1.8-R0.1-SNAPSHOT.jar:git-Bukkit-994b2aa]
	at net.minecraft.server.v1_8_R3.NetworkManager.l(NetworkManager.java:302) [craftbukkit-1.8-R0.1-SNAPSHOT.jar:git-Bukkit-994b2aa]
	at net.minecraft.server.v1_8_R3.ServerConnection.c(SourceFile:165) [craftbukkit-1.8-R0.1-SNAPSHOT.jar:git-Bukkit-994b2aa]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:748) [craftbukkit-1.8-R0.1-SNAPSHOT.jar:git-Bukkit-994b2aa]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:335) [craftbukkit-1.8-R0.1-SNAPSHOT.jar:git-Bukkit-994b2aa]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:632) [craftbukkit-1.8-R0.1-SNAPSHOT.jar:git-Bukkit-994b2aa]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:540) [craftbukkit-1.8-R0.1-SNAPSHOT.jar:git-Bukkit-994b2aa]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_73]
Caused by: java.lang.NoClassDefFoundError: net/md_5/bungee/api/ChatColor
	at com.scarsz.discordsrv.PlayerLeaveListener.PlayerQuitEvent(PlayerLeaveListener.java:24) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_73]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[craftbukkit-1.8-R0.1-SNAPSHOT.jar:git-Bukkit-994b2aa]
	... 12 more
[01:13:29] [Server thread/INFO]: xDeeKay left the game.

**Comment by Scarsz** [comment]
Fixed in build 4, involved you running Craftbukkit when it was trying to use Spigot's ChatColor class

**Comment by antv199** [comment]
```
[ERROR] .... Could not pass event PlayerQuitEvent to DiscordSRV v1.21.2

github.scarsz.discordsrv.dependencies.kevinsawicki.http.HttpRequest$HttpRequestException: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure

at github.scarsz.discordsrv.dependencies.kevinsawicki.http.HttpRequest.code(HttpRequest.java:1562) ~[?:?]

at github.scarsz.discordsrv.dependencies.mojang.Mojang.fetch(Mojang.java:81) ~[?:?]

at github.scarsz.discordsrv.DiscordSRV.getAvatarUrl(DiscordSRV.java:1892) ~[?:?]

at github.scarsz.discordsrv.DiscordSRV.getAvatarUrl(DiscordSRV.java:1883) ~[?:?]

at github.scarsz.discordsrv.DiscordSRV.sendLeaveMessage(DiscordSRV.java:1697) ~[?:?]

at github.scarsz.discordsrv.listeners.PlayerJoinLeaveListener.PlayerQuitEvent(PlayerJoinLeaveListener.java:132) ~[?:?]

at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor85.execute(Unknown Source) ~[?:?]

at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.4.jar:git-Paper-406]

at org.bukkit.plugin.EventExecutor$$Lambda$3676.0000000014944BD0.execute(Unknown Source) ~[?:?]

at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Paper-406]

at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Paper-406]

at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Paper-406]

at net.minecraft.server.v1_16_R3.PlayerList.disconnect(PlayerList.java:513) ~[patched_1.16.4.jar:git-Paper-406]

at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1690) ~[patched_1.16.4.jar:git-Paper-406]

at net.minecraft.server.v1_16_R3.NetworkManager.handleDisconnection(NetworkManager.java:502) ~[patched_1.16.4.jar:git-Paper-406]

at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:165) ~[patched_1.16.4.jar:git-Paper-406]

at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1376) ~[patched_1.16.4.jar:git-Paper-406]

at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-406]

at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1204) ~[patched_1.16.4.jar:git-Paper-406]

at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:992) ~[patched_1.16.4.jar:git-Paper-406]

at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.4.jar:git-Paper-406]

at net.minecraft.server.v1_16_R3.MinecraftServer$$Lambda$3147.0000000028186700.run(Unknown Source) ~[?:?]

at java.lang.Thread.run(Unknown Source) [?:?]

Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure

at sun.security.ssl.Alert.createSSLException(Unknown Source) ~[?:?]

at sun.security.ssl.Alert.createSSLException(Unknown Source) ~[?:?]

at sun.security.ssl.TransportContext.fatal(Unknown Source) ~[?:?]

at sun.security.ssl.Alert$AlertConsumer.consume(Unknown Source) ~[?:?]

at sun.security.ssl.TransportContext.dispatch(Unknown Source) ~[?:?]

at sun.security.ssl.SSLTransport.decode(Unknown Source) ~[?:?]

at sun.security.ssl.SSLSocketImpl.decode(Unknown Source) ~[?:?]

at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source) ~[?:?]

at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source) ~[?:?]

at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source) ~[?:?]

at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source) ~[?:?]

at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[?:?]

at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[?:?]

at java.net.HttpURLConnection.getResponseCode(Unknown Source) ~[?:?]

at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source) ~[?:?]

at github.scarsz.discordsrv.dependencies.kevinsawicki.http.HttpRequest.code(HttpRequest.java:1560) ~[?:?]

... 22 more
```

**Comment by Vankka** [comment]
@antv199, open a new issue instead of bumping a unrelated one that is almost 5 years old
