### ISSUE TITLE
Build 17 config error

### ISSUE THREAD

**Issue by CraftYourWay** [Scarsz/DiscordSRV#105]
```
[14:59:41] [Server thread/ERROR]: Error occurred while enabling DiscordSRV v13.0 (Is it up to date?)
java.lang.IllegalArgumentException: resource config.yml not found.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:148) ~[lobby.jar:git-Spigot-f950f8e-eb6c1bf]
	at com.google.common.io.Resources.getResource(Resources.java:229) ~[lobby.jar:git-Spigot-f950f8e-eb6c1bf]
	at github.scarsz.discordsrv.DiscordSRV.util.ResourceUtil.getResourceAsString(ResourceUtil.java:30) ~[?:?]
	at github.scarsz.discordsrv.DiscordSRV.objects.Config.<init>(Config.java:27) ~[?:?]
	at github.scarsz.discordsrv.DiscordSRV.Manager.<init>(Manager.java:55) ~[?:?]
	at github.scarsz.discordsrv.DiscordSRV.platforms.bukkit.BukkitPlatform.onEnable(BukkitPlatform.java:116) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[lobby.jar:git-Spigot-f950f8e-eb6c1bf]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [lobby.jar:git-Spigot-f950f8e-eb6c1bf]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [lobby.jar:git-Spigot-f950f8e-eb6c1bf]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:375) [lobby.jar:git-Spigot-f950f8e-eb6c1bf]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:325) [lobby.jar:git-Spigot-f950f8e-eb6c1bf]
	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:419) [lobby.jar:git-Spigot-f950f8e-eb6c1bf]
	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:380) [lobby.jar:git-Spigot-f950f8e-eb6c1bf]
	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:335) [lobby.jar:git-Spigot-f950f8e-eb6c1bf]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272) [lobby.jar:git-Spigot-f950f8e-eb6c1bf]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:542) [lobby.jar:git-Spigot-f950f8e-eb6c1bf]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
```

**Comment by Scarsz** [comment]
Resources have been a regular occurrence of annoyance and aren't ready to be user tested yet, soon though
