### ISSUE TITLE
PremiumVanish

### ISSUE THREAD

**Issue by random1167** [Scarsz/DiscordSRV#16]
````
[02:32:20 WARN]: java.lang.NullPointerException
[02:32:20 WARN]:        at de.myzelyam.premiumvanish.bukkit.utilities.BukkitUtils.getOnlineVanishedPlayers(BukkitUtils.java:206)
[02:32:20 WARN]:        at de.myzelyam.api.vanish.VanishAPI.getInvisiblePlayers(VanishAPI.java:23)
[02:32:20 WARN]:        at com.scarsz.discordsrv.hooks.PremiumVanish.isVanished(PremiumVanish.java:8)
[02:32:20 WARN]:        at com.scarsz.discordsrv.VanishedPlayerCheck.checkPlayerIsVanished(VanishedPlayerCheck.java:15)
[02:32:20 WARN]:        at com.scarsz.discordsrv.DiscordSRV.getOnlinePlayers(DiscordSRV.java:520)
[02:32:20 WARN]:        at com.scarsz.discordsrv.threads.ChannelTopicUpdater.applyFormatters(ChannelTopicUpdater.java:57)
[02:32:20 WARN]:        at com.scarsz.discordsrv.threads.ChannelTopicUpdater.run(ChannelTopicUpdater.java:29)
[02:32:20 WARN]: java.lang.NullPointerException
[02:32:20 INFO]: *** issued server command: /plugman unload PremiumVanish
[02:32:20 WARN]:        at de.myzelyam.premiumvanish.bukkit.utilities.BukkitUtils.getOnlineVanishedPlayers(BukkitUtils.java:206)
[02:32:20 WARN]:        at de.myzelyam.api.vanish.VanishAPI.getInvisiblePlayers(VanishAPI.java:23)
[02:32:20 WARN]:        at com.scarsz.discordsrv.hooks.PremiumVanish.isVanished(PremiumVanish.java:8)
[02:32:20 WARN]:        at com.scarsz.discordsrv.VanishedPlayerCheck.checkPlayerIsVanished(VanishedPlayerCheck.java:15)
[02:32:20 WARN]:        at com.scarsz.discordsrv.DiscordSRV.getOnlinePlayers(DiscordSRV.java:520)
[02:32:20 WARN]:        at com.scarsz.discordsrv.threads.ChannelTopicUpdater.applyFormatters(ChannelTopicUpdater.java:57)
[02:32:20 WARN]:        at com.scarsz.discordsrv.threads.ChannelTopicUpdater.run(ChannelTopicUpdater.java:29)
[02:32:20 WARN]: java.lang.NullPointerException
[02:32:20 WARN]:        at de.myzelyam.premiumvanish.bukkit.utilities.BukkitUtils.getOnlineVanishedPlayers(BukkitUtils.java:206)
[02:32:20 WARN]:        at de.myzelyam.api.vanish.VanishAPI.getInvisiblePlayers(VanishAPI.java:23)
[02:32:20 WARN]:        at com.scarsz.discordsrv.hooks.PremiumVanish.isVanished(PremiumVanish.java:8)
[02:32:20 WARN]:        at com.scarsz.discordsrv.VanishedPlayerCheck.checkPlayerIsVanished(VanishedPlayerCheck.java:15)
[02:32:20 WARN]:        at com.scarsz.discordsrv.DiscordSRV.getOnlinePlayers(DiscordSRV.java:520)
[02:32:20 WARN]:        at com.scarsz.discordsrv.threads.ChannelTopicUpdater.applyFormatters(ChannelTopicUpdater.java:57)
[02:32:20 WARN]:        at com.scarsz.discordsrv.threads.ChannelTopicUpdater.run(ChannelTopicUpdater.java:29)
[02:32:20 WARN]: java.lang.NullPointerException
[02:32:20 WARN]:        at de.myzelyam.premiumvanish.bukkit.utilities.BukkitUtils.getOnlineVanishedPlayers(BukkitUtils.java:206)
[02:32:20 WARN]:        at de.myzelyam.api.vanish.VanishAPI.getInvisiblePlayers(VanishAPI.java:23)
[02:32:20 INFO]: [PremiumVanish] Disabling PremiumVanish v1.5.1
[02:32:20 WARN]:        at com.scarsz.discordsrv.hooks.PremiumVanish.isVanished(PremiumVanish.java:8)
[02:32:20 WARN]:        at com.scarsz.discordsrv.VanishedPlayerCheck.checkPlayerIsVanished(VanishedPlayerCheck.java:15)
[02:32:20 WARN]:        at com.scarsz.discordsrv.DiscordSRV.getOnlinePlayers(DiscordSRV.java:520)
[02:32:20 WARN]:        at com.scarsz.discordsrv.threads.ChannelTopicUpdater.applyFormatters(ChannelTopicUpdater.java:57)
[02:32:20 WARN]:        at com.scarsz.discordsrv.threads.ChannelTopicUpdater.run(ChannelTopicUpdater.java:29)
[02:32:26 INFO]: __ issued server command: /warp ag
[02:32:40 INFO]: __ issued server command: /money
[02:33:08 INFO]: __ issued server command: /is go
[02:35:26 INFO]: Fetching all players.......
```
Spams the console

**Comment by Scarsz** [comment]
You unloaded PremiumVanish while DiscordSRV was trying to use it to check the player count, not much more I can say. https://github.com/Scarsz/DiscordSRV/commit/a5996f9aab8c0bc4213282d823d03bb0cbb73864
