### ISSUE TITLE
[FATAL ERROR] DiscordSRV Console Channel gets disconnected.

### ISSUE THREAD

**Issue by RedEyedRocker** [Scarsz/DiscordSRV#164]
## **Hello,**
_So I've noticed that sometimes I get some fatal error and my discord console channel then disconnects but the discord chat channel still works except for the console. After the error, nothing updates on the discord console channel. I had to reload the discordsrv plugin to get the console channel working again._

## **_Here's the error:_**
```[Wed Apr 05 21:19:00 MDT 2017 WARN] [21:19:00] [Fatal] [JDARequester]: Encountered an exception:
[Wed Apr 05 21:19:00 MDT 2017 WARN] [21:19:00] [Fatal] [JDARequester]: com.mashape.unirest.http.exceptions.UnirestException: java.net.SocketException: Connection reset
    at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:143)
    at com.mashape.unirest.request.BaseRequest.asString(BaseRequest.java:56)
    at com.scarsz.discordsrv.jda.requests.Requester.exec(Requester.java:92)
    at com.scarsz.discordsrv.jda.requests.Requester.post(Requester.java:57)
    at com.scarsz.discordsrv.jda.entities.impl.TextChannelImpl$AsyncMessageSender$Runner.run(TextChannelImpl.java:762)
Caused by: java.net.SocketException: Connection reset
    at java.net.SocketInputStream.read(SocketInputStream.java:210)
    at java.net.SocketInputStream.read(SocketInputStream.java:141)
    at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
    at sun.security.ssl.InputRecord.read(InputRecord.java:503)
    at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
    at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:930)
    at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
    at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:136)
    at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:152)
    at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:270)
    at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
    at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
    at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:260)
    at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:161)
    at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:153)
    at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:271)
    at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
    at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:254)
    at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
    at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
    at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
    at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
    at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:138)
    ... 4 more
```

**Comment by Scarsz** [comment]
I don't support versions <13 anymore, sorry. Update your plugin.

**Comment by RedEyedRocker** [comment]
But I'm using the version 13.3

**Comment by Scarsz** [comment]
You're not; version 13's changes included changing the package name to `github.scarsz.discordsrv`; the package in your error is `com.scarsz.discordsrv`. Another v13 change was upgrading to JDA 3, one of the mentioned classes in that stack trace is a class that was replaced in JDA 3 and doesn't exist anymore.

**Comment by RedEyedRocker** [comment]
Weird, I already have downloaded and even rated on the v13.3
I'll re-download it again.

**Comment by Scarsz** [comment]
Another note: ***do not reload DiscordSRV*** especially when updating it. You need to completely restart the server.

**Comment by RedEyedRocker** [comment]
No, I used plugman to reload it. Also, this happened even after multiple whole server restart.

**Comment by Scarsz** [comment]
Doesn't matter what you use to reload it. Don't. If it happened after full server restarts, you never replaced the plugin.

**Comment by RedEyedRocker** [comment]
Yeah, I'm going to right now and then check.

**Comment by RedEyedRocker** [comment]
```
05.04 23:29:20 [Server] INFO [JDA] Connected to WebSocket
05.04 23:29:20 [Server] INFO Save Statz database.
05.04 23:29:21 [Server] INFO [JDA] Finished Loading!
05.04 23:29:21 [Server] INFO Found server G:AcidCraft Network(277717531140030464)
05.04 23:29:21 [Server] INFO - TC:hub(280675741853810689)
05.04 23:29:21 [Server] INFO - TC:announcements(280774255430467584)
05.04 23:29:21 [Server] INFO - TC:guest_chat(287154197999255562)
05.04 23:29:21 [Server] INFO - TC:members_chat(277717531140030464)
05.04 23:29:21 [Server] INFO - TC:staff_chat(298038319131131905)
05.04 23:29:21 [Server] INFO - TC:music(288030968332288001)
05.04 23:29:21 [Server] INFO - TC:minecraft_chat(280774483881623552)
05.04 23:29:21 [Server] INFO - TC:minecraft_console(280772258073542656)
05.04 23:29:21 [Server] INFO - TC:reddit(280678941709303808)
05.04 23:29:21 [Server] INFO - TC:privategroupchat(293623918827143169)
05.04 23:29:21 [Server] INFO Console forwarding assigned to channel TC:minecraft_console(280772258073542656)
05.04 23:29:21 [Server] WARN No channels have been linked
05.04 23:29:21 [Server] INFO No chat plugin hooks enabled
05.04 23:29:21 [Server] INFO Colors: {3498DB=&3, 71368A=&5, 95A5A6=&7, AD1457=&d, 11806A=&2, 206694=&1, 1ABC9C=&a, 992D22=&4, E67E22=&6, A84300=&6, E74C3C=&c, 2ECC71=&a, 979C9F=&7, 607D8B=&8, 99AAB5=&f, F1C40F=&e, 1F8B4C=&2, E91E63=&d, 9B59B6=&5, C27C0E=&6, 546E7A=&8}
```

**Comment by RedEyedRocker** [comment]
I've set chat channel but it doesn't recognize it.

**Comment by Scarsz** [comment]
Join the Discord guild for help with this.
