### ISSUE TITLE
Issue on Spigot 1.12-pre2

### ISSUE THREAD

**Issue by mb243** [Scarsz/DiscordSRV#182]
```
[18:02:52] [ReadingThread/INFO]: [DiscordSRV] [JDA] Connected to WebSocket
[18:02:52] [ReadingThread/INFO]: [DiscordSRV] [JDA] Finished Loading!
[18:02:52] [DiscordSRV - Initialization/INFO]: [DiscordSRV] Found server G:[redacted]
[18:02:52] [DiscordSRV - Initialization/INFO]: [DiscordSRV] - TC:[redacted]
[18:02:52] [DiscordSRV - Initialization/INFO]: [DiscordSRV] - TC:[redacted]
[18:02:52] [DiscordSRV - Initialization/INFO]: [DiscordSRV] - TC:[redacted]
[18:02:52] [DiscordSRV - Initialization/INFO]: [DiscordSRV] - TC:[redacted]
[18:02:52] [DiscordSRV - Initialization/INFO]: [DiscordSRV] - TC:[redacted]
[18:02:52] [DiscordSRV - Initialization/INFO]: [DiscordSRV] - TC:[redacted]
[18:02:52] [DiscordSRV - Initialization/INFO]: [DiscordSRV] Console forwarding assigned to channel TC:[redacted]
[18:02:52] [DiscordSRV - Initialization/WARN]: Exception in thread "DiscordSRV - Initialization"
[18:02:52] [DiscordSRV - Initialization/WARN]: java.lang.NoSuchMethodError: org.apache.logging.log4j.core.layout.PatternLayout.createLayout(Ljava/lang/String;Lorg/apache/logging/log4j/core/config/Configuration;Lorg/apache/logging/log4j/core/pattern/RegexReplacement;Ljava/lang/String;Ljava/lang/String;)Lorg/apache/logging/log4j/core/layout/PatternLayout;
[18:02:52] [DiscordSRV - Initialization/WARN]:  at github.scarsz.discordsrv.objects.ConsoleAppender.<init>(ConsoleAppender.java:24)
[18:02:52] [DiscordSRV - Initialization/WARN]:  at github.scarsz.discordsrv.DiscordSRV.init(DiscordSRV.java:302)
[18:02:52] [DiscordSRV - Initialization/WARN]:  at java.lang.Thread.run(Thread.java:748)
```

**Comment by Scarsz** [comment]
1. Channel IDs are not sensitive info & thus do not need to be redacted
2. Already been fixed. https://github.com/Scarsz/DiscordSRV/commit/96432ddc98dae013f8f7840f27b56bd639c43895 https://github.com/Scarsz/DiscordSRV/commit/b3596c7aced5201e6eaf50833160a54bffc13d37 https://github.com/Scarsz/DiscordSRV/commit/4b586bef7f2391ec2940b8bfcc87003e25610f3d
