### ISSUE TITLE
Exception during shutdown

### ISSUE THREAD

**Issue by LemADEC** [Scarsz/DiscordSRV#199]
As of DiscordSRV v14.3, exception are reported during server shutdown (Cauldron/Thermos 1.7.10):

```
16:20:44 INFO]: [DiscordSRV] Disabling DiscordSRV v14.3
[16:20:44 ERROR]: Error occurred while disabling DiscordSRV v14.3 (Is it up to date?)
java.lang.NoClassDefFoundError: github/scarsz/discordsrv/util/DiscordUtil
>       at github.scarsz.discordsrv.DiscordSRV.onDisable(DiscordSRV.java:492) ~[?:?]
>       at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:318) ~[JavaPlugin.class:1.7.10-1614.57]
>       at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:392) [JavaPluginLoader.class:1.7.10-1614.57]
>       at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:429) [SimplePluginManager.class:1.7.10-1614.57]
>       at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:422) [SimplePluginManager.class:1.7.10-1614.57]
>       at org.bukkit.craftbukkit.v1_7_R4.CraftServer.disablePlugins(CraftServer.java:387) [CraftServer.class:1.7.10-1614.57]
>       at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:572) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:755) [MinecraftServer.class:?]
>       at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.ClassNotFoundException: Failed to remap class github.scarsz.discordsrv.util.DiscordUtil
>       at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:534) ~[PluginClassLoader.class:1.7.10-1614.57]
>       at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:455) ~[PluginClassLoader.class:1.7.10-1614.57]
>       at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:211) ~[PluginClassLoader.class:1.7.10-1614.57]
>       at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_121]
>       at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_121]
>       ... 9 more
Caused by: java.lang.IllegalArgumentException: INVOKESPECIAL/STATIC on interfaces require ASM 5
>       at org.objectweb.asm.MethodVisitor.visitMethodInsn(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
>       at org.objectweb.asm.ClassReader.a(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
>       at org.objectweb.asm.ClassReader.b(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
>       at org.objectweb.asm.ClassReader.accept(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
>       at org.objectweb.asm.ClassReader.accept(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
>       at net.md_5.specialsource.JarRemapper.remapClassFile(JarRemapper.java:246) ~[JarRemapper.class:?]
>       at net.md_5.specialsource.JarRemapper.remapClassFile(JarRemapper.java:232) ~[JarRemapper.class:?]
>       at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:499) ~[PluginClassLoader.class:1.7.10-1614.57]
>       at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:455) ~[PluginClassLoader.class:1.7.10-1614.57]
>       at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:211) ~[PluginClassLoader.class:1.7.10-1614.57]
>       at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_121]
>       at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_121]
>       ... 9 more
```

Same with 14.0:
```
[16:29:18 INFO]: [DiscordSRV] Disabling DiscordSRV v14.0
[16:29:18 ERROR]: Error occurred while disabling DiscordSRV v14.0 (Is it up to date?)
java.lang.NoClassDefFoundError: github/scarsz/discordsrv/util/DiscordUtil
>       at github.scarsz.discordsrv.DiscordSRV.onDisable(DiscordSRV.java:491) ~[?:?]
>       at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:318) ~[JavaPlugin.class:1.7.10-1614.57]
>       at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:392) [JavaPluginLoader.class:1.7.10-1614.57]
>       at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:429) [SimplePluginManager.class:1.7.10-1614.57]
>       at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:422) [SimplePluginManager.class:1.7.10-1614.57]
>       at org.bukkit.craftbukkit.v1_7_R4.CraftServer.disablePlugins(CraftServer.java:387) [CraftServer.class:1.7.10-1614.57]
>       at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:572) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:755) [MinecraftServer.class:?]
>       at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.ClassNotFoundException: Failed to remap class github.scarsz.discordsrv.util.DiscordUtil
>       at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:534) ~[PluginClassLoader.class:1.7.10-1614.57]
>       at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:455) ~[PluginClassLoader.class:1.7.10-1614.57]
>       at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:211) ~[PluginClassLoader.class:1.7.10-1614.57]
>       at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_121]
>       at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_121]
>       ... 9 more
Caused by: java.lang.IllegalArgumentException: INVOKESPECIAL/STATIC on interfaces require ASM 5
>       at org.objectweb.asm.MethodVisitor.visitMethodInsn(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
>       at org.objectweb.asm.ClassReader.a(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
>       at org.objectweb.asm.ClassReader.b(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
>       at org.objectweb.asm.ClassReader.accept(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
>       at org.objectweb.asm.ClassReader.accept(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
>       at net.md_5.specialsource.JarRemapper.remapClassFile(JarRemapper.java:246) ~[JarRemapper.class:?]
>       at net.md_5.specialsource.JarRemapper.remapClassFile(JarRemapper.java:232) ~[JarRemapper.class:?]
>       at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:499) ~[PluginClassLoader.class:1.7.10-1614.57]
>       at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:455) ~[PluginClassLoader.class:1.7.10-1614.57]
>       at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:211) ~[PluginClassLoader.class:1.7.10-1614.57]
>       at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_121]
>       at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_121]
>       ... 9 more
```

**Comment by LemADEC** [comment]
Same issue with 13.6:
```
[08:07:10 ERROR]: Error occurred while disabling DiscordSRV v13.6 (Is it up to date?)
java.lang.NoClassDefFoundError: github/scarsz/discordsrv/util/DiscordUtil
>       at github.scarsz.discordsrv.DiscordSRV.onDisable(DiscordSRV.java:467) ~[?:?]
>       at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:318) ~[JavaPlugin.class:1.7.10-1614.57]
>       at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:392) [JavaPluginLoader.class:1.7.10-1614.57]
>       at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:429) [SimplePluginManager.class:1.7.10-1614.57]
>       at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:422) [SimplePluginManager.class:1.7.10-1614.57]
>       at org.bukkit.craftbukkit.v1_7_R4.CraftServer.disablePlugins(CraftServer.java:387) [CraftServer.class:1.7.10-1614.57]
>       at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:572) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:755) [MinecraftServer.class:?]
>       at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.ClassNotFoundException: Failed to remap class github.scarsz.discordsrv.util.DiscordUtil
>       at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:534) ~[PluginClassLoader.class:1.7.10-1614.57]
>       at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:455) ~[PluginClassLoader.class:1.7.10-1614.57]
>       at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:211) ~[PluginClassLoader.class:1.7.10-1614.57]
>       at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_121]
>       at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_121]
>       ... 9 more
Caused by: java.lang.IllegalArgumentException: INVOKESPECIAL/STATIC on interfaces require ASM 5
>       at org.objectweb.asm.MethodVisitor.visitMethodInsn(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
>       at org.objectweb.asm.ClassReader.a(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
>       at org.objectweb.asm.ClassReader.b(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
>       at org.objectweb.asm.ClassReader.accept(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
>       at org.objectweb.asm.ClassReader.accept(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
>       at net.md_5.specialsource.JarRemapper.remapClassFile(JarRemapper.java:246) ~[JarRemapper.class:?]
>       at net.md_5.specialsource.JarRemapper.remapClassFile(JarRemapper.java:232) ~[JarRemapper.class:?]
>       at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:499) ~[PluginClassLoader.class:1.7.10-1614.57]
>       at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:455) ~[PluginClassLoader.class:1.7.10-1614.57]
>       at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:211) ~[PluginClassLoader.class:1.7.10-1614.57]
>       at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_121]
>       at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_121]
>       ... 9 more
```

**Comment by VankkaGithub** [comment]
ASM 5....

Instructions for updating to ASM5: (WARNING! `libraries` might be `bin` in some versions of KCauldron!)
1. Navigate to the libraries\net\md-5\SpecialSource\1.7-SNAPSHOT folder of the server
2. Delete the SpecialSource-1.7-SNAPSHOT.jar jar file
3. Download SpecialSource v1.7.4 from http://central.maven.org/maven2/net/md-5/SpecialSource/1.7.4/SpecialSource-1.7.4.jar
4. Copy the jar file to the libraries\net\md-5\SpecialSource\1.7-SNAPSHOT folder
5. Rename the jar file you just copied to SpecialSource-1.7-SNAPSHOT.jar

**Comment by LemADEC** [comment]
Thanks, that worked!
For the record, the wiki is asking the same here: https://github.com/Scarsz/DiscordSRV/wiki#the-plugin-crashs-at-serverstart-reporting-javalangnoclassdeffounderror-comscarszdiscordsrvjdamanagersaccountmanager
