### ISSUE TITLE
Crash on start (java.lang.ArrayIndexOutOfBoundsException: 38)

### ISSUE THREAD

**Issue by david50407** [Scarsz/DiscordSRV#205]
DiscordSRV version: 14.4

debug info: https://gist.github.com/100cc43f39a00bca23ca059eedc151f2

```
21:20:40 [ERROR] [DiscordSRV] DiscordSRV failed to load properly: 38. We've made a debug report with useful information, report your issue and provide this url: https://gist.github.com/100cc43f39a00bca23ca059eedc151f2
21:20:40 [WARN] java.lang.ArrayIndexOutOfBoundsException: 38
21:20:40 [WARN]         at github.scarsz.discordsrv.dependencies.jda.core.etf.EtfWriter.writeStringBytes(EtfWriter.java:127)
21:20:40 [WARN]         at github.scarsz.discordsrv.dependencies.jda.core.etf.EtfWriter.writeObject(EtfWriter.java:48)
21:20:40 [WARN]         at github.scarsz.discordsrv.dependencies.jda.core.etf.EtfWriter.writeMap(EtfWriter.java:147)
21:20:40 [WARN]         at github.scarsz.discordsrv.dependencies.jda.core.etf.EtfWriter.writeObject(EtfWriter.java:50)
21:20:40 [WARN]         at github.scarsz.discordsrv.dependencies.jda.core.etf.EtfWriter.writeMap(EtfWriter.java:147)
21:20:40 [WARN]         at github.scarsz.discordsrv.dependencies.jda.core.etf.EtfWriter.writeObject(EtfWriter.java:50)
21:20:40 [WARN]         at github.scarsz.discordsrv.dependencies.jda.core.etf.EtfWriter.writeMap(EtfWriter.java:147)
21:20:40 [WARN]         at github.scarsz.discordsrv.dependencies.jda.core.etf.EtfWriter.writeObject(EtfWriter.java:50)
21:20:40 [WARN]         at github.scarsz.discordsrv.dependencies.jda.core.etf.EtfWriter.writeMessage(EtfWriter.java:25)
21:20:40 [WARN]         at github.scarsz.discordsrv.dependencies.jda.core.etf.EtfWriter.writeMessage(EtfWriter.java:36)
21:20:40 [WARN]         at github.scarsz.discordsrv.dependencies.jda.core.requests.WebSocketClient.send(WebSocketClient.java:173)
21:20:40 [WARN]         at github.scarsz.discordsrv.dependencies.jda.core.managers.impl.PresenceImpl.update(PresenceImpl.java:245)
21:20:40 [WARN]         at github.scarsz.discordsrv.dependencies.jda.core.managers.impl.PresenceImpl.setPresence(PresenceImpl.java:122)
21:20:40 [WARN]         at github.scarsz.discordsrv.dependencies.jda.core.managers.impl.PresenceImpl.setGame(PresenceImpl.java:94)
21:20:40 [WARN]         at github.scarsz.discordsrv.util.DiscordUtil.setGameStatus(DiscordUtil.java:378)
21:20:40 [WARN]         at github.scarsz.discordsrv.DiscordSRV.init(DiscordSRV.java:309)
21:20:40 [WARN]         at java.lang.Thread.run(Thread.java:748)
```

**Comment by MaxiMiniJaniJos** [comment]
It seems that your config is outdated but that shouldn't cause a problem because of config migration.
You are better of coming to the discord and creating a ticket there.
scarsz.me/discord

**Comment by david50407** [comment]
I updated the config and the same problem still there, the debug info is here: 
https://gist.github.com/anonymous/24adacb852ea0e25a40cd0c3ca08c9df

When I downgrade to 14.3 with the updated config, it works well.

**Comment by Scarsz** [comment]
ETF JDA no longer being used, issue will be fixed in next update. Forwarding this to JDA
