### ISSUE TITLE
I think there is something wrong with 14.4

### ISSUE THREAD

**Issue by nexus671** [Scarsz/DiscordSRV#207]
14.3 is working fine while 14.4 causes heap issues

```
[11:56:21] [DiscordSRV - Console Message Queue Worker/WARN]: Exception in thread "DiscordSRV - Console Message Queue Worker" 
[11:56:21] [DiscordSRV - Console Message Queue Worker/WARN]: java.lang.OutOfMemoryError: Java heap space
[11:56:21] [DiscordSRV - Console Message Queue Worker/WARN]: 	at java.util.Arrays.copyOf(Arrays.java:3332)
[11:56:21] [DiscordSRV - Console Message Queue Worker/WARN]: 	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
[11:56:21] [DiscordSRV - Console Message Queue Worker/WARN]: 	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
[11:56:21] [DiscordSRV - Console Message Queue Worker/WARN]: 	at java.lang.StringBuilder.append(StringBuilder.java:136)
[11:56:21] [DiscordSRV - Console Message Queue Worker/WARN]: 	at github.scarsz.discordsrv.util.DiscordUtil.strip(DiscordUtil.java:116)
[11:56:21] [DiscordSRV - Console Message Queue Worker/WARN]: 	at github.scarsz.discordsrv.util.DiscordUtil.sendMessage(DiscordUtil.java:175)
[11:56:21] [DiscordSRV - Console Message Queue Worker/WARN]: 	at github.scarsz.discordsrv.util.DiscordUtil.sendMessage(DiscordUtil.java:146)
[11:56:21] [DiscordSRV - Console Message Queue Worker/WARN]: 	at github.scarsz.discordsrv.objects.threads.ConsoleMessageQueueWorker.run(ConsoleMessageQueueWorker.java:28)
```

**Comment by Scarsz** [comment]
we know

**Comment by Scarsz** [comment]
please test http://ci.scarsz.me/job/DiscordSRV/lastSuccessfulBuild/artifact/target/DiscordSRV-Build-14.5-SNAPSHOT-64.jar
