### ISSUE TITLE
Illegal mix of collations　Error?

### ISSUE THREAD

**Issue by xSoukazex** [Scarsz/DiscordSRV#215]
When starting the server, the following error occurs from DiscordSRV.

[11:26:20 WARN]: java.sql.SQLException: Illegal mix of collations (latin1_general_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '='
[11:26:20 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:959)
[11:26:20 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3870)
[11:26:20 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3806)
[11:26:20 WARN]:        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2470)
[11:26:20 WARN]:        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2617)
[11:26:20 WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2550)
[11:26:20 WARN]:        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
[11:26:20 WARN]:        at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1962)
[11:26:20 WARN]:        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
[11:26:20 WARN]:        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
[11:26:20 WARN]:        at uk.co.oliwali.HawkEye.database.DataManager.getKeyId(DataManager.java:136)
[11:26:20 WARN]:        at uk.co.oliwali.HawkEye.database.Consumer.run(Consumer.java:83)
[11:26:20 WARN]:        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
[11:26:20 WARN]:        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[11:26:20 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[11:26:20 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[11:26:20 WARN]:        at java.lang.Thread.run(Thread.java:745)

**Comment by Scarsz** [comment]
HawkEye issue, not DiscordSRV
