### ISSUE TITLE
Join issues

### ISSUE THREAD

**Issue by xSoukazex** [Scarsz/DiscordSRV#216]
I am sorry. I made a mistake. Here is the right one

```
[11:53:07 ERROR]: Could not pass event PlayerJoinEvent to DiscordSRV v14.7
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.PlayerList.onPlayerJoin(PlayerList.java:333) [spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.PlayerList.a(PlayerList.java:159) [spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
        at protocolsupport.protocol.packet.handler.AbstractLoginListener.b(AbstractLoginListener.java:159) [ProtocolSupport.jar:?]
        at protocolsupport.protocol.packet.handler.AbstractLoginListener.E_(AbstractLoginListener.java:103) [ProtocolSupport.jar:?]
        at net.minecraft.server.v1_10_R1.NetworkManager.a(NetworkManager.java:233) [spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.ServerConnection.c(ServerConnection.java:140) [spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:827) [spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.NullPointerException
        at github.scarsz.discordsrv.util.GroupSynchronizationUtil.reSyncGroups(GroupSynchronizationUtil.java:42) ~[?:?]
        at github.scarsz.discordsrv.util.GroupSynchronizationUtil.reSyncGroups(GroupSynchronizationUtil.java:34) ~[?:?]
        at github.scarsz.discordsrv.listeners.PlayerJoinLeaveListener.PlayerJoinEvent(PlayerJoinLeaveListener.java:36) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_101]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
        ... 14 more
```

And

```
[11:52:04 WARN]: [DiscordSRV] Plugin DiscordSRV v14.7 generated an exception while executing task 737
java.lang.NullPointerException
        at github.scarsz.discordsrv.util.GroupSynchronizationUtil.reSyncGroups(GroupSynchronizationUtil.java:42) ~[?:?]
        at github.scarsz.discordsrv.util.GroupSynchronizationUtil.reSyncGroups(GroupSynchronizationUtil.java:34) ~[?:?]
        at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_101]
        at github.scarsz.discordsrv.util.GroupSynchronizationUtil.lambda$static$0(GroupSynchronizationUtil.java:30) ~[?:?]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.10.2.jar:git-Spigot-de459a2-51263e9]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_101]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_101]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
```

**Comment by Scarsz** [comment]
Similar errors, has already been fixed
