### ISSUE TITLE
DiscordSRV 1.53 spamming errors on start up

### ISSUE THREAD

**Issue by TheRealPear** [Scarsz/DiscordSRV#249]
I am running on the latest version and getting this error on startup. Is it because of the new categories?

```
23.09 17:26:56 [Server] WARN [pool-17-thread-1] WARN de.btobastian.javacord.utils.PacketHandler - Couldn't handle packet of type CHANNEL_UPDATE. Please contact the developer! (packet: {"is_private":false,"permission_overwrites":[{"allow":72704,"deny":0,"id":"352968810128474113","type":"role"},{"allow":72704,"deny":0,"id":"354254653103538186","type":"role"},{"allow":72704,"deny":0,"id":"352575119773925379","type":"role"},{"allow":0,"deny":5120,"id":"352487451903918095","type":"role"}],"last_message_id":"361184741602361346","nsfw":false,"parent_id":"361139527055572992","name":"direcraft-console","guild_id":"352487451903918095","topic":"TPS: 20.0 | Mem: 1.2GB used/1.2GB free/2.5GB max | 1.12.1-R0.1-SNAPSHOT","position":6,"id":"352732985625280512","type":"text"}) 23.09 17:26:56 [Server] WARN java.lang.NullPointerException 
23.09 17:26:56 [Server] WARN at de.btobastian.javacord.utils.handler.channel.ChannelUpdateHandler.a(Unknown Source) 
23.09 17:26:56 [Server] WARN at de.btobastian.javacord.utils.handler.channel.ChannelUpdateHandler.handle(Unknown Source) 23.09 17:26:56 [Server] WARN at de.btobastian.javacord.utils.c.run(Unknown Source) 23.09 17:26:56 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 23.09 17:26:56 [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:266) 23.09 17:26:56 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) 23.09 17:26:56 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) 23.09 17:26:56 [Server] WARN at java.lang.Thread.run(Thread.java:745)
23.09 17:26:56 [Server] WARN [pool-17-thread-1] WARN de.btobastian.javacord.utils.PacketHandler - Couldn't handle packet of type CHANNEL_UPDATE. Please contact the developer! (packet: {"is_private":false,"permission_overwrites":[{"allow":66560,"deny":456768,"id":"354013812715814912","type":"role"},{"allow":72704,"deny":0,"id":"352920596113260577","type":"role"},{"allow":359488,"deny":163840,"id":"354414368764723202","type":"role"},{"allow":805829713,"deny":0,"id":"352575119773925379","type":"role"},{"allow":384064,"deny":0,"id":"354366582455009281","type":"role"},{"allow":130112,"deny":0,"id":"354256067066331136","type":"role"},{"allow":523328,"deny":0,"id":"352968810128474113","type":"role"},{"allow":15360,"deny":0,"id":"354254653103538186","type":"role"},{"allow":0,"deny":0,"id":"352921878123380747","type":"role"},{"allow":66560,"deny":456768,"id":"352487451903918095","type":"role"}],"last_message_id":"361186795934842882","nsfw":false,"parent_id":"361143155946553344","name":"direcraft-chat","guild_id":"352487451903918095","topic":"0/50 players online | 15 unique players ever joined | Server online for 0 minutes | Last update: Sat, 23. Sep 2017 17:26:56 BST","position":3,"id":"352503791511142401","type":"text"})
23.09 17:26:56 [Server] WARN java.lang.NullPointerException
23.09 17:26:56 [Server] WARN at de.btobastian.javacord.utils.handler.channel.ChannelUpdateHandler.a(Unknown Source) 23.09 
17:26:56 [Server] WARN at de.btobastian.javacord.utils.handler.channel.ChannelUpdateHandler.handle(Unknown Source) 
23.09 17:26:56 [Server] WARN at de.btobastian.javacord.utils.c.run(Unknown Source) 23.09 
17:26:56 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 
23.09 17:26:56 [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:266)
23.09 17:26:56 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
23.09 17:26:56 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
23.09 17:26:56 [Server] WARN at java.lang.Thread.run(Thread.java:745)
```

**Comment by Scarsz** [comment]
Whatever plugin you're using to link your Discord and Minecraft servers together, DiscordSRV isn't it. Feel free to switch as this is an issue that's been fixed for us.

**Comment by TheRealPear** [comment]
I'm already using DiscordSRV and a friend of mine ticketed this on your Discord, he said that you told him that it was fixed.

**Comment by Scarsz** [comment]
This is an error regarding the library called Javacord. DiscordSRV does not use Javacord. This ticket is the only place I've seen Javacord mentioned in the past month.
