### ISSUE TITLE
1.9 Spigot - DiscordSRV Release 7

### ISSUE THREAD

**Issue by creativetux** [Scarsz/DiscordSRV#3]
Minecraft to Discord channel works perfectly, however Discord to Minecraft generates this error:

```
[13:13:07 WARN]: [13:13:07] [Fatal] [JDASocket]: Encountered an exception:
[13:13:07 WARN]: java.lang.NullPointerException
[13:13:07 WARN]:        at com.scarsz.discordsrv.DiscordListener.handleChat(DiscordListener.java:125)
[13:13:07 WARN]:        at com.scarsz.discordsrv.DiscordListener.onMessageReceived(DiscordListener.java:46)
[13:13:07 WARN]:        at net.dv8tion.jda.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:179)
[13:13:07 WARN]:        at net.dv8tion.jda.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:54)
[13:13:07 WARN]:        at net.dv8tion.jda.handle.MessageReceivedHandler.handle(MessageReceivedHandler.java:58)
[13:13:07 WARN]:        at net.dv8tion.jda.requests.WebSocketClient.onTextMessage(WebSocketClient.java:166)
[13:13:07 WARN]:        at com.neovisionaries.ws.client.ListenerManager.callOnTextMessage(ListenerManager.java:352)
[13:13:07 WARN]:        at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:233)
[13:13:07 WARN]:        at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:211)
[13:13:07 WARN]:        at com.neovisionaries.ws.client.ReadingThread.handleTextFrame(ReadingThread.java:910)
[13:13:07 WARN]:        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:693)
[13:13:07 WARN]:        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:102)
[13:13:07 WARN]:        at com.neovisionaries.ws.client.ReadingThread.run(ReadingThread.java:61)

```

**Comment by Scarsz** [comment]
Already has been fixed on build 7.1
