### ISSUE TITLE
Not Loading

### ISSUE THREAD

**Issue by Roadhog360** [Scarsz/DiscordSRV#328]
On my Thermos 1.7.10 server, the plugin will not load:
```
[23:52:12] [Server thread/ERROR]: Could not load 'plugins/DiscordSRV-Build-1.16.1.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: github/scarsz/discordsrv/dependencies/google/common/collect/Sets$1
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:149) ~[JavaPluginLoader.class:1.7.10-1614.57]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:334) ~[SimplePluginManager.class:1.7.10-1614.57]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:256) [SimplePluginManager.class:1.7.10-1614.57]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugins(CraftServer.java:343) [CraftServer.class:1.7.10-1614.57]
	at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:462) [ayq.class:?]
	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:138) [ayq.class:?]
	at net.minecraft.world.World.<init>(World.java:374) [ahb.class:?]
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:162) [mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:375) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:337) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.NoClassDefFoundError: github/scarsz/discordsrv/dependencies/google/common/collect/Sets$1
	at github.scarsz.discordsrv.dependencies.reflections.util.ConfigurationBuilder.<init>(ConfigurationBuilder.java:56) ~[?:?]
	at github.scarsz.discordsrv.objects.managers.CommandManager.<init>(CommandManager.java:49) ~[?:?]
	at github.scarsz.discordsrv.DiscordSRV.<init>(DiscordSRV.java:87) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_151]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_151]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_151]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_151]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:201) ~[PluginClassLoader.class:1.7.10-1614.57]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) ~[JavaPluginLoader.class:1.7.10-1614.57]
	... 11 more
Caused by: java.lang.ClassNotFoundException: Failed to remap class github.scarsz.discordsrv.dependencies.google.common.collect.Sets$1
	at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:534) ~[PluginClassLoader.class:1.7.10-1614.57]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:455) ~[PluginClassLoader.class:1.7.10-1614.57]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:211) ~[PluginClassLoader.class:1.7.10-1614.57]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_151]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_151]
	at github.scarsz.discordsrv.dependencies.reflections.util.ConfigurationBuilder.<init>(ConfigurationBuilder.java:56) ~[?:?]
	at github.scarsz.discordsrv.objects.managers.CommandManager.<init>(CommandManager.java:49) ~[?:?]
	at github.scarsz.discordsrv.DiscordSRV.<init>(DiscordSRV.java:87) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_151]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_151]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_151]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_151]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:201) ~[PluginClassLoader.class:1.7.10-1614.57]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) ~[JavaPluginLoader.class:1.7.10-1614.57]
	... 11 more
Caused by: java.lang.IllegalArgumentException: INVOKESPECIAL/STATIC on interfaces require ASM 5
	at org.objectweb.asm.MethodVisitor.visitMethodInsn(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
	at org.objectweb.asm.ClassReader.a(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
	at org.objectweb.asm.ClassReader.b(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
	at org.objectweb.asm.ClassReader.accept(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
	at org.objectweb.asm.ClassReader.accept(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
	at net.md_5.specialsource.JarRemapper.remapClassFile(JarRemapper.java:246) ~[JarRemapper.class:?]
	at net.md_5.specialsource.JarRemapper.remapClassFile(JarRemapper.java:232) ~[JarRemapper.class:?]
	at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:499) ~[PluginClassLoader.class:1.7.10-1614.57]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:455) ~[PluginClassLoader.class:1.7.10-1614.57]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:211) ~[PluginClassLoader.class:1.7.10-1614.57]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_151]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_151]
	at github.scarsz.discordsrv.dependencies.reflections.util.ConfigurationBuilder.<init>(ConfigurationBuilder.java:56) ~[?:?]
	at github.scarsz.discordsrv.objects.managers.CommandManager.<init>(CommandManager.java:49) ~[?:?]
	at github.scarsz.discordsrv.DiscordSRV.<init>(DiscordSRV.java:87) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_151]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_151]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_151]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_151]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:201) ~[PluginClassLoader.class:1.7.10-1614.57]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) ~[JavaPluginLoader.class:1.7.10-1614.57]
	... 11 more
```

**Comment by Androkai** [comment]
Please check this one: https://github.com/Scarsz/DiscordSRV/wiki/FAQ#fix-for-thermos

**Comment by Roadhog360** [comment]
Hm... I'll try this. Thank you.

**Comment by Roadhog360** [comment]
So, now I have a new issue. I get massive 'Unknown command. Type "/help" for help.' spam in the chat. It is very fast and sends clusters of these a few times a second.
I tried turning off that one config option, but it does not exist for me.

**Comment by Androkai** [comment]
In most cases spam from another plugin but we need for information what command it is etc.
Also you're welcome to join [our discord server](https://discordapp.com/invite/au3S5q3) and report your problem in #support channel for faster response times.
