### ISSUE TITLE
Spams somethings that I can't use the console 

### ISSUE THREAD

**Issue by superkarli9** [Scarsz/DiscordSRV#359]
Since yesterday I have a problem with the plugin it spams :

```
[Sat, 30. Jun 2018 19:37:04 EET WARN] java.net.UnknownHostException: discordapp.com
[Sat, 30. Jun 2018 19:37:04 EET WARN] 	at java.net.InetAddress.getAllByName0(InetAddress.java:1280)
[Sat, 30. Jun 2018 19:37:04 EET WARN] 	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
[Sat, 30. Jun 2018 19:37:04 EET WARN] 	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
[Sat, 30. Jun 2018 19:37:04 EET WARN] 	at github.scarsz.discordsrv.dependancies.okhttp3.Dns$1.lookup(Dns.java:39)
[Sat, 30. Jun 2018 19:37:04 EET WARN] 	at github.scarsz.discordsrv.dependancies.okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:171)
[Sat, 30. Jun 2018 19:37:04 EET WARN] 	at github.scarsz.discordsrv.dependancies.okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:137)
[Sat, 30. Jun 2018 19:37:04 EET WARN] 	at github.scarsz.discordsrv.dependancies.okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:82)
[Sat, 30. Jun 2018 19:37:04 EET WARN] 	at github.scarsz.discordsrv.dependancies.okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:171)
[Sat, 30. Jun 2018 19:37:04 EET WARN] 	at github.scarsz.discordsrv.dependancies.okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
[Sat, 30. Jun 2018 19:37:04 EET WARN] 	at github.scarsz.discordsrv.dependancies.okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
[Sat, 30. Jun 2018 19:37:04 EET WARN] 	at github.scarsz.discordsrv.dependancies.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
[Sat, 30. Jun 2018 19:37:04 EET WARN] 	at github.scarsz.discordsrv.dependancies.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
[Sat, 30. Jun 2018 19:37:04 EET WARN] 	at github.scarsz.discordsrv.dependancies.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
```

**Comment by Scarsz** [comment]
Your server's DNS failed. Wait it out or switch to a different DNS server.
