### ISSUE TITLE
Error at startup - ClassNotFoundException

### ISSUE THREAD

**Issue by Androkai** [Scarsz/DiscordSRV#48]
```
[13:46:06] [Server thread/ERROR]: Could not load 'plugins/DiscordSRV.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: com/scarsz/discordsrv/google/common/collect/Lists
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[craftbukkit_baucraft.jar:git-Spigot-90f61bc-5e5cf84]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[craftbukkit_baucraft.jar:git-Spigot-90f61bc-5e5cf84]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [craftbukkit_baucraft.jar:git-Spigot-90f61bc-5e5cf84]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugins(CraftServer.java:297) [craftbukkit_baucraft.jar:git-Spigot-90f61bc-5e5cf84]
        at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:203) [craftbukkit_baucraft.jar:git-Spigot-90f61bc-5e5cf84]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535) [craftbukkit_baucraft.jar:git-Spigot-90f61bc-5e5cf84]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
Caused by: java.lang.NoClassDefFoundError: com/scarsz/discordsrv/google/common/collect/Lists
        at com.scarsz.discordsrv.objects.CancellationDetector.<init>(CancellationDetector.java:23) ~[?:?]
        at com.scarsz.discordsrv.DiscordSRV.<clinit>(DiscordSRV.java:82) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_102]
        at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_102]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[craftbukkit_baucraft.jar:git-Spigot-90f61bc-5e5cf84]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[craftbukkit_baucraft.jar:git-Spigot-90f61bc-5e5cf84]
        ... 6 more
Caused by: java.lang.ClassNotFoundException: com.scarsz.discordsrv.google.common.collect.Lists
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_102]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[craftbukkit_baucraft.jar:git-Spigot-90f61bc-5e5cf84]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[craftbukkit_baucraft.jar:git-Spigot-90f61bc-5e5cf84]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_102]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_102]
        at com.scarsz.discordsrv.objects.CancellationDetector.<init>(CancellationDetector.java:23) ~[?:?]
        at com.scarsz.discordsrv.DiscordSRV.<clinit>(DiscordSRV.java:82) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_102]
        at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_102]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[craftbukkit_baucraft.jar:git-Spigot-90f61bc-5e5cf84]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[craftbukkit_baucraft.jar:git-Spigot-90f61bc-5e5cf84]
        ... 6 more
```

**Comment by Scarsz** [comment]
https://github.com/Scarsz/DiscordSRV/commit/693962f33f7cd75382caf2fb05a58c771fb524a4
