### ISSUE TITLE
Cannot set to an empty path

### ISSUE THREAD

**Issue by xorinzor** [Scarsz/DiscordSRV#98]
Version: 12.3
Our discord plugin doesn't want to load, reviewing the logs tells us this:

```
java.lang.IllegalArgumentException: Cannot set to an empty path
	at org.apache.commons.lang.Validate.notEmpty(Validate.java:321) ~[Validate.class:2.6]
	at org.bukkit.configuration.MemorySection.set(MemorySection.java:163) ~[MemorySection.class:1.7.10-1614.57]
	at org.bukkit.configuration.file.YamlConfiguration.convertMapsToSections(YamlConfiguration.java:80) ~[YamlConfiguration.class:1.7.10-1614.57]
	at org.bukkit.configuration.file.YamlConfiguration.convertMapsToSections(YamlConfiguration.java:78) ~[YamlConfiguration.class:1.7.10-1614.57]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:68) ~[YamlConfiguration.class:1.7.10-1614.57]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:226) ~[FileConfiguration.class:1.7.10-1614.57]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:169) ~[FileConfiguration.class:1.7.10-1614.57]
	at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:180) ~[YamlConfiguration.class:1.7.10-1614.57]
	at org.bukkit.plugin.java.JavaPlugin.reloadConfig(JavaPlugin.java:183) ~[JavaPlugin.class:1.7.10-1614.57]
	at org.bukkit.plugin.java.JavaPlugin.getConfig(JavaPlugin.java:157) ~[JavaPlugin.class:1.7.10-1614.57]
	at com.scarsz.discordsrv.DiscordSRV.onEnable(DiscordSRV.java:107) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:1.7.10-1614.57]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:1.7.10-1614.57]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-1614.57]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:438) [CraftServer.class:1.7.10-1614.57]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:372) [CraftServer.class:1.7.10-1614.57]
	at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:519) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:493) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:453) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:337) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
```

I don't think this is something caused by our config files, but if it is, what could be causing it?

**Comment by Scarsz** [comment]
More than definitely your config, specifically canned responses

**Comment by xorinzor** [comment]
Ah, yeah it seems someone didn't properly set the value, I just didn't notice it while scrolling through.
Knowing where to look specifically definitely helped :) thanks!
